// <auto-generated />
using DiscordAuth.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DiscordAuth.Database.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiscordAuth.Database.DivisionGuild", b =>
                {
                    b.Property<decimal>("Snowflake")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("GcaRole")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("HqStaffRole")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("MemberRole")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("StaffRole")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("VisitorRole")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Snowflake");

                    b.ToTable("Divisions");
                });

            modelBuilder.Entity("DiscordAuth.Database.User", b =>
                {
                    b.Property<string>("Vid")
                        .HasColumnType("text");

                    b.Property<decimal>("Snowflake")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Vid");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
